,pyvovar,localhost.localdomain,25.04.2019 21:42,file:///home/pyvovar/.config/libreoffice/4;